### ISSUE TITLE
web map

### ISSUE THREAD

**Issue by kateregga1** [osmafrica/sotm-africa-2019-website#6]
Can we add a web map to the venue?

**Comment by enockseth** [comment]
Sure we can

**Comment by enockseth** [comment]
@Hills95 can you fork and add this?

**Comment by denironyx** [comment]
Hi @Hills95, what's the update. Have you made any process so far? 

@enockseth, have you followed up on the web map section?

**Comment by Hills95** [comment]
Can someone share with me the exact coordinates of the conference location?

**Comment by enockseth** [comment]
@Fanevanjanahary Get someone from LOC to respond to this.

**Comment by fanevanjanahary** [comment]
`{
  "type": "FeatureCollection",
  "features": [
    {
      "type": "Feature",
      "properties": {
        "name": "Beach"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          -3.737841,
          5.195079
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "_umap_options": {
          "color": "Red",
          "iconClass": "Drop"
        },
        "name": "VITIB"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          -3.759041,
          5.227985
        ]
      }
    }
  ]
}`

**Comment by enockseth** [comment]
#36
