### ISSUE TITLE
Add Kaart as Bronze sponsor 

### ISSUE THREAD

**Issue by enockseth** [osmafrica/sotm-africa-2019-website#68]
**Website**: https://kaartgroup.com/

![](https://kaartgroup.com/wp-content/uploads/2019/09/Kaart-Final-Logo_Horizontal.png)

**Comment by fanevanjanahary** [comment]
Can you please share the Kaart website and the logo. Thank you

**Comment by enockseth** [comment]
I see @kateregga1 following up on this. I have updated issue description
